name: Generate Profile Metrics SVG

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate metrics SVG
        uses: lowlighter/metrics@v3
        with:
          filename: dist/metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, repositories
          config_timezone: UTC
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      - name: Commit & Push (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/metrics.svg || true
          if git diff --cached --quiet; then
            echo "No metric changes"
          else
            git commit -m "chore: update profile metrics svg"
            git push
          fi