name: Update Recent Activity

on:
  schedule:
    - cron: '5 * * * *'  # hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch recent activity
        uses: Readme-Workflows/recent-activity@v2
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 10
          TARGET_FILE: README.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          # Section markers
          START_COMMENT: '<!-- ACTIVITY:START -->'
          END_COMMENT: '<!-- ACTIVITY:END -->'
