name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours (more freshness)
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVG variants
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: List generated files
        run: ls -l dist || find . -maxdepth 2 -type f -name "snake*.svg"

      - name: Commit & Push (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/snake*.svg || true
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update contribution snake"
            git push
          fi
