name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # every day 00:00 UTC
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/contribution-snake.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/contribution-snake.svg || true
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update contribution snake"
            git push
          fi
